// site/components/ProjectShowcase.vue
<script setup lang="ts">
const projects = [
  {
    title: 'CADAC SQL Visualizer',
    description:
      'A SQL syntax tree visualizer that allows users to visualize and understand the structure of SQL queries.',
    url: 'https://sql.janhoon.com',
  },
]
</script>

<template>
  <div>
    <h3 class="text-2xl font-bold mb-4">Featured Projects</h3>
    <div class="space-y-4">
      <div
        v-for="(project, index) in projects"
        :key="project.title"
        v-motion
        :initial="{ opacity: 0, scale: 0.9 }"
        :enter="{ opacity: 1, scale: 1, transition: { duration: 300, delay: index * 100 } }"
        class="p-4 rounded border-b last:border-b-0"
      >
        <a :href="project.url" class="hover:text-green-500">
          <h4 class="font-bold">{{ project.title }}</h4>
          <p class="text-sm text-gray-600">{{ project.description }}</p>
        </a>
      </div>
    </div>
  </div>
</template>

// site/src/components/ProjectShowcase.tsx
import { motion } from "framer-motion";

export default function ProjectShowcase() {
  const projects = [
    {
      title: "CADAC SQL Visualizer",
      description:
        "A SQL syntax tree visualizer that allows users to visualize and understand the structure of SQL queries.",
      url: "https://sql.janhoon.com",
    },
  ];

  return (
    <div>
      <h3 className="text-2xl font-bold mb-4">Featured Projects</h3>
      <div className="space-y-4">
        {projects.map((project, index) => (
          <motion.div
            key={project.title}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3, delay: index * 0.1 }}
            className="p-4 rounded border-b last:border-b-0"
          >
            <a href={project.url} className="hover:text-green-500">
              <h4 className="font-bold">{project.title}</h4>
              <p className="text-sm text-gray-600">{project.description}</p>
            </a>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
