// site/components/SocialLinks.vue
<script setup lang="ts">
const socialLinks = [
  { icon: 'mdi:linkedin', url: 'https://www.linkedin.com/in/janhoon' },
  { icon: 'mdi:github', url: 'https://github.com/janhoon' },
  { icon: 'ri:twitter-x-fill', url: 'https://x.com/janhendrikhoon' },
]
</script>

<template>
  <div
    v-motion
    :initial="{ opacity: 0, x: 50 }"
    :enter="{ opacity: 1, x: 0, transition: { duration: 500 } }"
    class="fixed top-4 right-4 flex flex-col space-y-4"
  >
    <a
      v-for="link in socialLinks"
      :key="link.url"
      :href="link.url"
      target="_blank"
      rel="noopener noreferrer"
      class="text-gray-100 hover:text-gray-300 hover:scale-120 active:scale-90 transition-transform"
    >
      <Icon :name="link.icon" class="w-6 h-6" />
    </a>
  </div>
</template>

// site/src/components/SocialLinks.tsx
import { motion } from "framer-motion"
import { Github, Linkedin, Twitter } from "lucide-react"

export default function SocialLinks() {
  const socialLinks = [
    { icon: <Linkedin size={24} />, url: "https://www.linkedin.com/in/janhoon" },
    { icon: <Twitter size={24} />, url: "https://twitter.com/janhoon" },
    { icon: <Github size={24} />, url: "https://github.com/janhoon" },
  ]

  return (
    <motion.div
      initial={{ opacity: 0, x: 50 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ duration: 0.5 }}
      className="fixed top-4 right-4 flex flex-col space-y-4"
    >
      {socialLinks.map((link) => (
        <motion.a
          key={link.url}
          href={link.url}
          target="_blank"
          rel="noopener noreferrer"
          whileHover={{ scale: 1.2 }}
          whileTap={{ scale: 0.9 }}
          className="text-gray-100 hover:text-gray-300"
        >
          {link.icon}
        </motion.a>
      ))}
    </motion.div>
  )
}
