// site/src/components/BlogTitle.tsx
import Link from "next/link";

export default function BlogTitle({
	title,
	date,
	author,
}: { title: string; date: string; author: { name: string; url: string } }) {
	return (
		<div className="flex flex-col items-start justify-between w-full">
			<h1 className="text-md md:text-2xl font-bold mb-4">{title}</h1>
			<Link href={author.url} className="text-sm text-gray-400">
				by <span className="font-bold text-lg text-green-600 hover:text-green-500 hover:underline">{author.name}</span>
			</Link>
			<span className="text-sm text-gray-400">{date}</span>
		</div>
	);
}

// site/components/BlogTitle.vue
<script setup lang="ts">
defineProps<{
  title: string
  date: string
  authorName: string
  authorUrl: string
}>()
</script>

<template>
  <div class="flex flex-col items-start justify-between w-full">
    <h1 class="text-4xl font-bold mb-4">{{ title }}</h1>
    <NuxtLink :to="authorUrl" class="text-lg text-gray-400">
      by
      <span class="font-bold text-xl text-green-600 hover:text-green-500 hover:underline">
        {{ authorName }}
      </span>
    </NuxtLink>
    <span class="text-lg text-gray-400">{{ date }}</span>
  </div>
</template>
